### ISSUE TITLE
Feature:  Flag to format the output 

### ISSUE THREAD

**Issue by mischah** [sindresorhus/date-now-cli#1]
I have a use case for formatted output. And didn’t find a matching CLI for that.
It would be nice this one could handle that.

## Proposal

```
$ date-now --format "DD.MM.YYYY"
25.04.2018

$ date-now --format "YYY:MM:DD"
2018:04:25
```

**Valid patterns**

+ `YYYY`: Full year
+ `MM`: Month (example: 04)
+ `DD`: Day (example: 01)
+ `HH`: Hours (example: 14)
+ `mm`: Minutes (example: 59)
+ `ss`: Seconds (example: 09)
+ `SSS`: Milliseconds (example: 532)

Not sure about the patterns though. It’s a subset auf the format options of:

- [date-fns](https://date-fns.org/v1.29.0/docs/format)
- [Moment.js](https://momentjs.com/docs/#/displaying/format/)

**Comment by sindresorhus** [comment]
Yeah, would be useful. PR welcome.

I would prefer using https://date-fns.org/v1.29.0/docs/format

Should also add https://github.com/sindresorhus/meow then to handle argument parsing. Example: https://github.com/sindresorhus/delay-cli/blob/master/cli.js
